/Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/Main.o /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/Main.or /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/Main.od /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/Main.op:  \
 /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/Main.cc \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../utils/System.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../utils/../mtl/IntTypesMtl.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../utils/ParseUtils.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../utils/Options.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../utils/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../utils/../mtl/../mtl/IntTypesMtl.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../utils/../mtl/../mtl/XAlloc.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../utils/../utils/ParseUtils.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../core/Dimacs.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../core/../utils/ParseUtils.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../core/../core/SolverTypes.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../core/../core/../mtl/IntTypesMtl.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../core/../core/../mtl/Alg.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../core/../core/../mtl/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../core/../core/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../core/../core/../mtl/Map.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../core/../core/../mtl/../mtl/IntTypesMtl.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../core/../core/../mtl/Alloc.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../core/../core/../mtl/../mtl/XAlloc.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/SimpSolver.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../mtl/Queue.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../mtl/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/Solver.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../mtl/Heap.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../mtl/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../mtl/Alg.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../utils/Options.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../core/SolverTypes.h
/Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/SimpSolver.o /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/SimpSolver.or /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/SimpSolver.od /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/SimpSolver.op:  \
 /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/SimpSolver.cc \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../mtl/Sort.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../mtl/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../mtl/../mtl/../mtl/IntTypesMtl.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../mtl/../mtl/../mtl/XAlloc.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/SimpSolver.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../mtl/Queue.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../mtl/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/Solver.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../mtl/Heap.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../mtl/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../mtl/Alg.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../utils/Options.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../utils/../mtl/IntTypesMtl.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../utils/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../utils/../utils/ParseUtils.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../core/SolverTypes.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../core/../mtl/IntTypesMtl.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../core/../mtl/Alg.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../core/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../core/../mtl/Map.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../core/../mtl/../mtl/IntTypesMtl.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../core/../mtl/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../core/../mtl/Alloc.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../simp/../core/../core/../mtl/../mtl/XAlloc.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../utils/System.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/simp/../utils/../mtl/IntTypesMtl.h
/Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/Main.o /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/Main.or /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/Main.od /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/Main.op:  \
 /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/Main.cc \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../utils/System.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../utils/../mtl/IntTypesMtl.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../utils/ParseUtils.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../utils/Options.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../utils/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../utils/../mtl/../mtl/IntTypesMtl.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../utils/../mtl/../mtl/XAlloc.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../utils/../utils/ParseUtils.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/Dimacs.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../utils/ParseUtils.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../core/SolverTypes.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../core/../mtl/IntTypesMtl.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../core/../mtl/Alg.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../core/../mtl/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../core/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../core/../mtl/Map.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../core/../mtl/../mtl/IntTypesMtl.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../core/../mtl/Alloc.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../core/../mtl/../mtl/XAlloc.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/Solver.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../mtl/Heap.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../mtl/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../mtl/Alg.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../utils/Options.h
/Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/Solver.o /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/Solver.or /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/Solver.od /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/Solver.op:  \
 /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/Solver.cc \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../mtl/Sort.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../mtl/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../mtl/../mtl/../mtl/IntTypesMtl.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../mtl/../mtl/../mtl/XAlloc.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/Solver.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../mtl/Heap.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../mtl/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../mtl/Alg.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../utils/Options.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../utils/../mtl/IntTypesMtl.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../utils/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../utils/../utils/ParseUtils.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../core/SolverTypes.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../core/../mtl/IntTypesMtl.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../core/../mtl/Alg.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../core/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../core/../mtl/Map.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../core/../mtl/../mtl/IntTypesMtl.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../core/../mtl/../mtl/Vec.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../core/../mtl/Alloc.h \
  /Users/james/Documents/school/12/Fall/CMSC631/p2/stp/src/sat/core/../core/../core/../mtl/../mtl/XAlloc.h
